engines:
  rubocop:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - ruby
ratings:
  paths:
    - lib/**
    - "**.rb"
exclude_paths:
  - bin/*
  - spec/**/*
  - "**/vendor/**/*"
